sudo: required
services:
    - docker

before_install:
    - docker build -t darshanadsw/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run darshanadsw/react-test npm test -- --coverage

after_success:
    - docker build -t darshanadsw/multi-client ./client
    - docker build -t darshanadsw/multi-nginx ./nginx
    - docker build -t darshanadsw/multi-server ./server
    - docker build -t darshanadsw/multi-worker ./worker
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push darshanadsw/multi-client
    - docker push darshanadsw/multi-nginx
    - docker push darshanadsw/multi-server
    - docker push darshanadsw/multi-worker